#4 added the possibility to use a function as the input to text with …
tableflip/react-native-toaster pull request #5
Opened 2017-07-26 11:28 UTC by bjartebore

…a callback method for hideToast, then we can provide our own logic for hiding toasts

2017-10-12 09:07 UTC, alanshaw requested changes
This looks great 🚀 thanks @bjartebore !

Could you please respond to the review queries and also update the docs on the README?

2017-10-12 09:07 UTC, alanshaw commented on src/Toast.js
> +  }
@bjartebore what does this do - is it a fix for #11?

2017-10-12 09:07 UTC, alanshaw commented on src/Toast.js
> +      textContent = text({ hide: this.hideToast });
Please remove semicolon so the linting rules pass

2017-10-12 09:08 UTC, alanshaw commented
Also, apologies for not looking at this sooner, for some reason notifications were switched off for me in this repo.

2017-10-18 05:13 UTC, kytwb commented
@bjartebore still working on this?

2020-10-06 15:40 UTC, closed without merging